version: '3.9'

x-logging:
  &loki-logging
  driver: loki
  options:
    loki-url: "http://192.168.55.20:3100/loki/api/v1/push"
    loki-batch-size: "400"
    loki-retries: "7"
    loki-timeout: "5s"

services:
  couper:
    image: avenga/couper-oidc-gateway
    container_name: couper
    ports:
      - 80:80
      - 443:443
    environment:
      - OIDC_CONFIGURATION_URL=${OIDC_CONFIGURATION_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - TOKEN_SECRET=${TOKEN_SECRET}
      - BACKEND_ORIGIN=${BACKEND_ORIGIN}
    restart: unless-stopped
    logging: *loki-logging

  watchtower:
    restart: unless-stopped
    container_name: WatchTower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=gotify
      - "WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://192.168.55.5:85"
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${GOTIFY_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 21600