version: '3.3'
services:
  collabora:
    image: collabora/code
    container_name: collabora_app
    cap_add:
      - MKNOD
    expose:
      - 9980
    environment:
      - domain=${COLLABORA_DOMAIN} #Gebt hier eure Nextcloud Domain an. Wenn ihr dies nicht nutzt, dann entfernt diese Zeile
      - username=${COLLABORA_USER}     #Nutzername eingeben
      - password=${COLLABORA_PASSWORD}         #Passwort eingeben
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=true"
    restart: unless-stopped