version: "3.9"

x-logging:
  &loki-logging
  driver: loki
  options:
    loki-url: "http://192.168.55.20:3100/loki/api/v1/push"
    loki-batch-size: "400"
    loki-retries: "7"
    loki-timeout: "5s"


  oauth2-proxy-nextcloud:
    image: bitnami/oauth2-proxy:latest
    command:
      - --http-address
      - 0.0.0.0:4180 
    environment:
      OAUTH2_PROXY_UPSTREAMS: ${UPSTREAM} 
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: ${NAME}
      OAUTH2_PROXY_PROVIDER: oidc 
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${ISSUER}
      OAUTH2_PROXY_CLIENT_ID: ${CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${CLIENT_SECRET}
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: true 
      OAUTH2_PROXY_EMAIL_DOMAINS: '*' 
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:4180/oauth2/callback 
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET} 
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: true 
      OAUTH2_PROXY_COOKIE_NAME: SESSION 
      OAUTH2_PROXY_COOKIE_SAMESITE: lax 
      OAUTH2_PROXY_SESSION_STORE_TYPE: redis 
      OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://proxy-nextcloud-redis
      OAUTH2_PROXY_REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - 4180:4180
    depends_on:
      - proxy-nextcloud-redis
    networks:
      - nextcloud-proxy
    logging: *loki-logging


  proxy-nextcloud-redis:
    image: redis:latest
    container_name: proxy-nextcloud-redis
    hostname: proxy-nextcloud-redis
    networks:
      - nextcloud-proxy
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    logging: *loki-logging


  agent:
    restart: unless-stopped
    container_name: PortainerAgent
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    networks:
      - net-portainer
    logging: *loki-logging

volumes:
  cache:

networks:
  nextcloud-proxy:
  net-portainer:

