version: "3.9"

x-logging:
  &loki-logging
  driver: loki
  options:
    loki-url: "http://192.168.55.20:3100/loki/api/v1/push"
    loki-batch-size: "400"
    loki-retries: "7"
    loki-timeout: "5s"


services:
  apache:
    image: httpd:latest
    container_name: static_site
    ports: 
        - '80:80'
        - '443:443'
    volumes:
      - static_data:/usr/local/apache2/htdocs
    restart: unless-stopped
    logging: *loki-logging
    networks:
      - net-static

  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - mariadb_data:/bitnami/mariadb
    environment:
      - MARIADB_PASSWORD=${WORDPRESS_DATABASE_PASSWORD}
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
    restart: unless-stopped
    logging: *loki-logging
    networks:
      - net-wp

  wordpress:
    image: docker.io/bitnami/wordpress:latest
    expose:
      - 8080
    volumes:
      - wordpress_data:/bitnami/wordpress
      - static_data:/data/website
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_PASSWORD=${WORDPRESS_DATABASE_PASSWORD}
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_PLUGINS=Simply Static
    restart: unless-stopped
    logging: *loki-logging
    networks:
      - net-wp

  oauth2-proxy:
    image: bitnami/oauth2-proxy:latest
    command:
      - --http-address
      - 0.0.0.0:4180
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://wordpress:8080
      OAUTH2_PROXY_PROVIDER_DISPLAY_NAME: ${OAUTH2_PROXY_PROVIDER_DISPLAY_NAME}
      OAUTH2_PROXY_PROVIDER: keycloak-oidc
      OAUTH2_PROXY_OIDC_ISSUER_URL: ${OAUTH2_PROXY_OIDC_ISSUER_URL}
      OAUTH2_PROXY_CLIENT_ID: ${OAUTH2_PROXY_CLIENT_ID}
      OAUTH2_PROXY_CLIENT_SECRET: ${OAUTH2_PROXY_CLIENT_SECRET}
      OAUTH2_PROXY_PASS_ACCESS_TOKEN: "true"
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_REDIRECT_URL: ${OAUTH2_PROXY_REDIRECT_DOMAIN}/oauth2/callback
      OAUTH2_PROXY_COOKIE_SECRET: ${OAUTH2_PROXY_COOKIE_SECRET}
      OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
      OAUTH2_PROXY_COOKIE_NAME: SESSION
      OAUTH2_PROXY_COOKIE_SAMESITE: lax
      OAUTH2_PROXY_SESSION_STORE_TYPE: redis
      OAUTH2_PROXY_REDIS_CONNECTION_URL: redis://redis
      OAUTH2_PROXY_REDIS_PASSWORD: ${REDIS_PASSWORD}
      OAUTH2_PROXY_ALLOWED_ROLES: ${OAUTH2_PROXY_ALLOWED_ROLES}
      OAUTH2_PROXY_COOKIE_REFRESH: 10s
    ports:
      - 4180:4180
    depends_on:
      - redis
    networks:
      - net-wp
    logging: *loki-logging


  redis:
    image: bitnami/redis:latest
    container_name: redis
    hostname: redis
    networks:
      - net-wp
    restart: unless-stopped
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_cache:/bitnami/redis/data
    logging: *loki-logging

  watchtower:
    restart: unless-stopped
    container_name: WatchTower
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_ROLLING_RESTART=true
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_NOTIFICATIONS=gotify
      - "WATCHTOWER_NOTIFICATION_GOTIFY_URL=http://192.168.55.5:85"
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${GOTIFY_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 21600
    logging: *loki-logging
    networks:
      - net-watchtower

  agent:
    restart: unless-stopped
    container_name: PortainerAgent
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - 9001:9001
    networks:
      - net-portainer
    logging: *loki-logging

volumes:
  wordpress_data:
  mariadb_data:
  static_data:
  redis_cache:

networks:
  net-wp:
  net-portainer:
  net-watchtower:
  net-static:

